params:
  ribao:
     updatePath: D:\SVN_Folder\天津SVN\Management(管理库)\SPTO(项目跟踪)\项目日报\2019
     checkOutPath: D:\account\ribao
     svnUrl: http://192.168.18.23:1980/svn/reins_svn/Management(管理库)/SPTO(项目跟踪)/项目日报/2019
     checkswitch: 1
     checkname: 刘春旭;刘晓宇;卢玥;周志伟;安广;常若男;张振环;张震;潘晨;王思铭;王艳艳;纪津;胡文达;董博宇;闫明
     specialworkday: 2020-01-01:0;2020-01-19:1;2020-01-24:0;2020-01-27:0;2020-01-28:0;2020-01-29:0;2020-01-30:0;2020-02-01:1;2020-04-06:0;2020-04-26:1;2020-05-01:0;2020-05-04:0;2020-05-05:0;2020-05-09:1;2020-06-25:0;2020-06-26:0;2020-06-28:1;2020-09-27:1;2020-10-01:0;2020-10-02:0;2020-10-05:0;2020-10-06:0;2020-10-07:0;2020-10-08:0;2020-10-10:1
  svn:
     username: zhaozhigang
     password: zhaozhigang
  email:
     sendemail: zhaozhigang@sinosoft.com.cn
     password: 784533Gigi
     receiveemail: zhaozhigang@sinosoft.com.cn
server:
  port: 8081
  name: RiBao

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/reinsdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: reins
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.ribao.po  # 注意：对应实体类的路径
logging:
  level:
    org:
      mybatis: DEBUG
      springframework:
        web: DEBUG
        transaction: DEBUG
        data: DEBUG
        security: DEBUG
    ins:
      platform: DEBUG
    com:
      github: DEBUG  

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

