params:
  ribao:
     filepath: D:\SVN_Folder\天津SVN\Management(管理库)\SPTO(项目跟踪)\项目日报\2019
     checkswitch: 0
     checkname: 刘春旭;刘晓宇;卢玥;周志伟;安广;常若男;张金梁;张震;潘晨;王思铭;王艳艳;纪津;胡文达;董博宇;闫明
     specialworkday: 2019-09-29:1;2019-10-01:0;2019-10-02:0;2019-10-03:0;2019-10-04:0;2019-10-05:0;2019-10-06:0;2019-10-07:0;2019-10-12:1
  svn:
     username: reins_server
     password: reins_server
  email:
     sendemail: zhaozhigang@sinosoft.com.cn
     password: 784533Gigi
     receiveemail: zhaozhigang@sinosoft.com.cn;zhangjinliang@sinosoft.com.cn
server:
  port: 8081
  name: RiBao
  


spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/reinsdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: reins
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.ribao.po  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

